apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
spec:
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springapp
          image: 408716684642.dkr.ecr.ap-south-1.amazonaws.com/springapp:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: tcp
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  selector:
    app: springapp
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer