spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webex
    username: dbuser
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true