spring:
  profiles:
    active:
    - dev
---

spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    url: jdbc:mysql://localhost:3306/webex
#    url: jdbc:mysql://mysql-db-aws.cjrba3xiwusx.ap-south-1.rds.amazonaws.com/webex
    username: dbuser
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true

---

spring:
  config:
    activate:
      on-profile:
      - test
  datasource:
    url: jdbc:h2:mem:webex
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true
      
---

spring:
  config:
    activate:
      on-profile:
      - prod
  datasource:
    url: jdbc:mysql://mysql-db-aws.cjrba3xiwusx.ap-south-1.rds.amazonaws.com/webex
    username: dbuser
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true